[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "utils"
version = "1.0.0"

[tool.setuptools.packages.find]
include = ["utils"]
exclude = ["tests", "tests.*"]